version: '3'

services:
  api:
    build: ./services/api/
    volumes:
      - ./services/api:/app:rw
  proxy:
    build: ./services/proxy/
    ports:
      - 80:80
  #client:
  #  build: ./services/client/
  #  volumes:
  #    - ./services/client:/app:rw
  #  ports:
  #    - 9999:9999 # For Hot Module Replacement (HMR)